name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # testing job to run tests
  test:
    runs-on: ubuntu-latest

    services:
      # mailhog:
      #   image: mailhog/mailhog
      #   ports:
      #     - 1025:1025   # SMTP PORT
      #     - 8025:8025   # Web UI PORT
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: campaignhub
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432   # map 5432 to avoid confusion
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/

      - name: Run migrations
        env:
          DB_ADDR: postgres://root:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/campaignhub?sslmode=disable
        run: make migrateup

      - name: Run tests
        env:
          WORKFLOW: true
          DB_ADDR: postgres://root:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/campaignhub?sslmode=disable
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: ${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME: campaignhub
          PASETO_ASYM_PRIV: ${{ secrets.PASETO_ASYM_PRIV }}
          PASETO_ASYM_PUB: ${{ secrets.PASETO_ASYM_PUB }}
          PASETO_SYM: ${{ secrets.PASETO_SYM }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: make test
